run_tests:
  script:
    - set +e # Disable exit on error
    - xvfb-run --server-args="-screen 0 1024x768x24" /usr/local/lib/unity3d/Editor/Unity -batchmode -projectPath "$(pwd)/Lumiere" -force-opengl -runTests -testPlatform playmode -testResults "$HOME/build_logs/playmode-$CI_JOB_ID.xml"
    - /usr/local/lib/unity3d/Editor/Unity -nographics -batchmode -projectPath "$(pwd)/Lumiere" -runTests -testPlatform editmode -testResults "$HOME/build_logs/editor-$CI_JOB_ID.xml"

after_script:
  - rm -r "$(pwd)/Lumiere"
  - git reset --hard HEAD
  - cp "$(pwd)/parse.hs" /tmp/parse.hs
  - ghc /tmp/parse.hs -o /tmp/parse
  - /tmp/parse $HOME/build_logs/{playmode,editor}-$CI_JOB_ID.xml
