before_script:
  - rm -rf "$(pwd)/PlayTestResults"
  - rm -rf "$(pwd)/EditTestResults"
  - mkdir "$(pwd)/PlayTestResults"
  - mkdir "$(pwd)/EditTestResults"

run_tests:
  script:
    - set +e # Disable exit on error
    - xvfb-run --server-args="-screen 0 1024x768x24" /usr/local/lib/unity3d/Editor/Unity -batchmode -projectPath "$(pwd)/Lumiere" -force-opengl -runTests -testPlatform playmode
    - set -e # Enable exit on error
    - mv "$(pwd)/Lumiere"/TestResults*.xml "$(pwd)/PlayTestResults/"
    - /usr/local/lib/unity3d/Editor/Unity -nographics -batchmode -projectPath "$(pwd)/Lumiere" -runTests -testPlatform editmode
    - mv "$(pwd)/Lumiere"/TestResults*.xml "$(pwd)/EditTestResults/"

after_script:
  - rm -r "$(pwd)/Lumiere"
  - git reset --hard HEAD
  - echo "Play test results"
  - cat "$(pwd)/PlayTestResults/"TestResults-*.xml
  - echo "Edit test results"
  - cat "$(pwd)/EditTestResults/"TestResults-*.xml
