run_tests:
  script:
    - set +e # Disable exit on error
    - xvfb-run --server-args="-screen 0 1024x768x24" /usr/local/lib/unity3d/Editor/Unity -batchmode -projectPath "$(pwd)/Lumiere" -force-opengl -runTests -testPlatform playmode -testResults "/root/build_logs/playmode-$CI_JOB_ID.xml"
    - set -e # Enable exit on error
    - /usr/local/lib/unity3d/Editor/Unity -nographics -batchmode -projectPath "$(pwd)/Lumiere" -runTests -testPlatform editmode -testResults "/root/build_logs/editor-$CI_JOB_ID.xml"

after_script:
  - rm -r "$(pwd)/Lumiere"
  - git reset --hard HEAD
  - echo "Play test results"
  - cat "/root/build_logs/playmode-$CI_JOB_ID.xml"
  - echo "Edit test results"
  - cat "/root/build_logs/editor-$CI_JOB_ID.xml"
